/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_droideye_Utils_JniUtils */

#ifndef _Included_com_example_administrator_droideye_Utils_JniUtils
#define _Included_com_example_administrator_droideye_Utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_droideye_Utils_JniUtils
 * Method:    hellojni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_droideye_Utils_JniUtils_hellojni
  (JNIEnv *, jobject);

int test();
#ifdef __cplusplus
}
#endif
#endif
